declare type SvgKey =
  | "401"
  | "Affiliate"
  | "announcement"
  | "chess"
  | "close"
  | "custom_service"
  | "expand"
  | "favorite-clicked"
  | "favorite-unclick"
  | "Favorites"
  | "filbet_original"
  | "fishing"
  | "help_center"
  | "History Icon"
  | "Home"
  | "left-arrow"
  | "live_casino"
  | "blog"
  | "play-icon"
  | "Promotions"
  | "r_usdt"
  | "rank1"
  | "rank2"
  | "rank3"
  | "Recent"
  | "right-arrow"
  | "search"
  | "slot_game"
  | "Sports"
  | "table_game"
  | "vip"
  
